Repository marceloFA/pycee2, pull requests merged in 2020-11, with the labels that each got.

#6 add handler for ModuleNotFoundError
  pycee/errors.py
Labels: errors-module

#10 Create GitHub Action to test and lint pull request to master branch. solves #7
  .github/workflows/python-app.yml
  requirements-dev.txt
  requirements.txt
Labels: ci/cd

#11 New handler for KeyError
  pycee/answers.py
  pycee/errors.py
  pycee/utils.py
  tests/test_errors.py
  usage.py
Labels: improving-solutions

#14 Traceback is now collected from source
  example_code.py
  example_error_msg.txt
  pycee/answers.py
  pycee/errors.py
  pycee/inspection.py
  pycee/sym_table.py
  pycee/utils.py
  setup.cfg
  setup.py
  tests/test_answers.py
  tests/test_errors.py
  tests/test_inspection.py
  usage.py
Labels: enhancement

#16 Configure package to be uploaded to PyPI
  .gitignore
  pycee/utils.py
  requirements.txt
  setup.py
  usage.py
Labels: enhancement

#28 Refactor work on error handlers
  pycee/errors.py
  pycee/inspection.py
  pycee/utils.py
  setup.py
  syntax_across_languages.json
  tests/test_error_handlers/test_key_error.py
  tests/test_error_handlers/test_module_not_found_error.py
  tests/test_error_handlers/test_name_error.py
  tests/test_errors.py
  usage.py
Labels: enhancement, refactor-work

#33 Add cache to functions that calls StackOverflow API
  .gitignore
  pycee/answers.py
  requirements.txt
  tests/test_answers.py
Labels: enhancement, first-release

#34 Refactor request for questions and answers
  pycee/answers.py
  pycee/errors.py
  pycee/inspection.py
  pycee/utils.py
  tests/test_answers.py
  tests/test_inspection.py
  usage.py
Labels: refactor-work
