Repository marceloFA/pycee2, pull requests merged in 2020-12, with the labels that each got.

#35 Add local handler for IndexError
  pycee/errors.py
  pycee/utils.py
  tests/test_error_handlers/test_index_error.py
Labels: improving-solutions

#38 Add SyntaxError handlers
  pycee/answers.py
  pycee/errors.py
  pycee/inspection.py
  pycee/sym_table.py
  pycee/utils.py
  requirements.txt
  tests/test_argparser.py
  tests/test_error_handlers/test_index_error.py
  tests/test_error_handlers/test_key_error.py
  tests/test_error_handlers/test_module_not_found_error.py
  tests/test_error_handlers/test_name_error.py
  tests/test_error_handlers/test_syntax_error.py
  tests/test_inspection.py
  usage.py
Labels: improving-solutions

#39 Bugfix: os.execvp to delete cache files
  pycee/utils.py
Labels: bug-fix

#40 Remove deprecated code
  pycee/answers.py
  pycee/errors.py
  pycee/sym_table.py
Labels: refactor-work

#42 Bugfix: default for Stackoverflow users with no profile image
  pycee/answers.py
  tests/test_answers.py
Labels: bug-fix

#43 Implement logic to retrieve questions from Google search engine
  pycee/answers.py
  pycee/errors.py
  pycee/utils.py
  requirements.txt
  tests/test_answers.py
  tests/test_argparser.py
  usage.py
Labels: improving-solutions
